### ISSUE TITLE
[BUG] error after completing a download on bioshock 2

### ISSUE THREAD

**Issue by Trokinos** [RareDevs/Rare#208]
Using the pip version of Rare on window 10
After completing the download of bioshock 2 , Rare showed this error : 
![123456](https://user-images.githubusercontent.com/14024168/171623281-6c092039-e86a-4be7-81e5-d3e83c45b2ff.jpg)

the "postinstall" part of the error may be related to what i see in the Legendary window as it seems the game ask for some additional installer to be run, but fail to do so :  
![222](https://user-images.githubusercontent.com/14024168/171623328-c0ba1502-0ef3-4822-8547-cf4820b4a5dd.jpg)

Fortunately it does not prevent the game to work for me (as i guess all those prerequisite involve various directx/mscv/etc... that i already have on my system)

**Comment by loathingKernel** [comment]
This has been fixed by https://github.com/Dummerle/Rare/commit/8b723f7fcc4422a269ce83bf201e909f0de9880d, we haven't done a release since.

**Comment by Bungwr** [comment]
when in the 2k launcher for me it says install and not play.. do you know how i could fix this? ty
