### ISSUE TITLE
[Feature Request] Download throttling

### ISSUE THREAD

**Issue by Foxydiot** [RareDevs/Rare#258]
**Is your feature request related to a problem? Please describe.**
I have fairly slow DSL internet. Because of this, I always throttled downloads in order to keep it at least slightly usable. Unfortunately though, this launcher does not have that.

**Describe the solution you'd like**
I would like to see a way to throttle download speeds in a freely adjustable amount.

**Describe alternatives you've considered**
I have considered using an additional piece of software that would throttle specific applications, but that's a bit overkill for me when it's just one application that requires this. I have also considered switching back to the official EG launcher but quickly dismissed that thought because that's such a terribly thought out launcher imo.

**Comment by loathingKernel** [comment]
Can't be done as `legendary` which we as the back-end doesn't support it. A workaround to this is using less workers to download.
