### ISSUE TITLE
When I do the login through browser thing I copied the link, I did not have an epic account at that time so I made one and when i finished making the Epic games account it redirected me to a page that was white and i read through it and I found the auth code to login so i copied it and pressed next and it said login failed. I have rare thing installed

### ISSUE THREAD

**Issue by WobbyBobby12355** [RareDevs/Rare#288]
<img width="500" alt="Screenshot 2023-05-15 184108" src="https://github.com/Dummerle/Rare/assets/133716353/c9fa5c4f-ce83-4504-8cfa-5daa22d3a320">

**Comment by loathingKernel** [comment]
Try again after verifying your email. Or simply try again. This is probably due to your account being too new. It is very unlikely it is a bug of Rare or Legendary.
