### ISSUE TITLE
Its says that api-ms-win-core-path-l1-0.dil is missing from my computer

### ISSUE THREAD

**Issue by Shreejeeth** [RareDevs/Rare#289]
Its says that api-ms-win-core-path-l1-0.dil is missing from my computer

![c9ef858c-fa8f-4261-8549-97ebcd23c82d](https://github.com/Dummerle/Rare/assets/134084213/d5bb84e4-108a-47e2-9481-51cf50bac758)

Windows 7 Ultimate

You can find logs in these locations
- Windows: `C:\Users\<username>\AppData\Local\Rare\Rare\cache\logs`
- Linux: `~/.cache/Rare/Rare/logs`

**Comment by Dummerle** [comment]
Windows 7 is not supported by Rare. You need at least Windows 8
