### ISSUE TITLE
[BUG] Getting OSError on Windows - invalid argument - not able to start 

### ISSUE THREAD

**Issue by xinelogit** [RareDevs/Rare#291]
**Describe the bug**
Getting below error everytime I start Rare on Windows 11.

**Error message**
> Traceback (most recent call last):
>   File "C:\hostedtoolcache\windows\Python\3.11.3\x64\Lib\site-packages\rare\shared\workers\worker.py", line 41, in run
>   File "C:\hostedtoolcache\windows\Python\3.11.3\x64\Lib\site-packages\rare\shared\workers\fetch.py", line 43, in run_real
>   File "C:\hostedtoolcache\windows\Python\3.11.3\x64\Lib\site-packages\legendary\core.py", line 521, in get_non_asset_library_items
>   File "C:\hostedtoolcache\windows\Python\3.11.3\x64\Lib\site-packages\legendary\lfs\lgndry.py", line 232, in set_game_meta
> OSError: [Errno 22] Invalid argument: 'C:\\Users\\xinel/.config/legendary\\metadata\\562d4a2c1b3147b089a7c453e3ddbcbe\t.json'

I have deleted config files several times and tried the two login methods with same error.

**Comment by loathingKernel** [comment]
Try it from here: https://github.com/loathingKernel/Rare/actions/runs/5089594257

Epic fucked up something, It has already been worked around.
