### ISSUE TITLE
[BUG] [flatpak] Crash On Start 

### ISSUE THREAD

**Issue by body20002** [RareDevs/Rare#305]
**Describe the bug**

**To Reproduce**

1. install flatpak rare
2. login using browser
3. crash

**Expected behavior**

no crash

**Screenshots**
![image](https://github.com/Dummerle/Rare/assets/33910565/da7c726b-d359-4745-8a21-bac7387cd30f)

**Comment by loathingKernel** [comment]
I recently encountered this.This is most likely a permission issue with the flatpak being unable to access the system's `PATH`. @body20002 you can use `flatseal` to modify the access permissions for other flatpaks. In case you are able to solve it through flathead it can help use update the package.

**Comment by body20002** [comment]
@loathingKernel I'm not sure what to do exactly adding `PATH=$PATH` in flatseal doesn't help

**Comment by body20002** [comment]
I think the problem is rare doesn't package wine other launcher like lutris and heroic package or at least give you a way to install and manage wine and proton through them and since I don't have wine installed in my system I can't launch rare because it checks for wine at the startup

so to fix this issue there are two solutions
either rare doesn't check for wine at the startup or do without crash but notify the user that wine is not found and asks the users to provide the path

or the second solution which I rather not do is install wine in my system

P.S. wine exists only in lutris, heroic and steam and I have them installed as a flatpak apps

**Comment by loathingKernel** [comment]
With Rare we made the conscious choice to not provide such functionality as downloading wine or proton versions. So far we are of the opinion that we do not want to do the job of a package manager since there are so many already and we do not want to waste the development effort required to do a sub-par job at it.

The check for wine at startup is part of detecting games installed through integrated third party clients, such as Origin, i.e. Star Wars Battlefront etc.

I am under the impression that we do check if wine is installed at startup and skip that step if it isn't but I will have to check again.

**Comment by loathingKernel** [comment]
We can probably check for more locations, but we do not want to hand-hold our users. It is up to the user to configure the wine version they want to use. What we should have done in this case is not run those checks if we didn't find the wine binary. We need both `wine` and `winepath` for that check to work and IIRC `proton` doesn't include it.

In that regard, there is also another extension to this issue, if you as the user selects a wine version which requires a specific runtime, such as lutris's wine, we do not necessarily configure the correct environment for that version, as we would also need to take care of things such as `LD_LIBRARY_PATH`. Such configuration also falls on the user.

In your specific case, you are also using a non-standard way to use steam(flatpak). So we not only have to include the regular paths but also the flatpak paths. This can get out of hand quickly as each and every one of these paths has to be checked. It becomes insane quite quickly.

**Comment by loathingKernel** [comment]
I have not used Steam, lutris or ProtonUp-Qt through flatpak. If you are still interested, could you provide some information for me?

When run through flatpak what are the locations where all these tools and runtimes are stored? Are they stored in each individual flatpak container or under the user's home directory?
To word it differently, are they accessible through `~/.local/share/Steam` and `~/.local/share/lutris`?

Also, what environment do the compatibility tools run in when run through flatpak'd Steam? From what I know, flathub provides a proton-ge package, which presumably doesn't use Steam's runtime, what about the other tools?
