### ISSUE TITLE
Android version of rare

### ISSUE THREAD

**Issue by franklinprakash1090** [RareDevs/Rare#367]
Please add rare library management client for Android because the epic games store doesn't have official Android app or library on website so implement Android app
It is use full to confirm free claiming games on mobile

**Comment by loathingKernel** [comment]
As far as I know, epic doesn't offer android versions of their games in their Epic Games Launcher, which makes Rare on Android mostly pointless. I do not know of any way to run Windows games on Android either.

For claiming free games on Android, a separate application might be a better alternative, but I do not know how possible it is to claim games outside of the website.

**Comment by franklinprakash1090** [comment]
Not for claiming but for Library management like the steam and third party gog library management app

**Comment by Angell1993** [comment]
There is an Epic Games app for Android..
https://store.epicgames.com/en-US/download/android

But I don't use it myself, but it is available..
