### ISSUE TITLE
[Feature Request] UI Scaling options/changes via possible QT Libraries update

### ISSUE THREAD

**Issue by rjbprime** [RareDevs/Rare#368]
**Is your feature request related to a problem? Please describe.**

The ability to scale Rare UI via command-line options, startup parameters, or options in the client, with working results.

**Describe the solution you'd like**

Opening windows CMD prompt in the installed directory, typing  ``set QT_AUTO_SCREEN_SCALE_FACTOR=0 & set QT_SCALE_FACTOR=0.5 & rare.exe``, then having Rare open, should scale the UI (text, pictures, etc.) to 50% size, for those with smaller screens, or those who, like me, are nutjobs with UI settings, and wish to view more content.

**Describe alternatives you've considered**

I haven't considered any other alternatives.

**Additional context**

Screenshot of desktop at native 1920x1080, with Rare set to described settings.

![RareScalingScreenshot](https://github.com/RareDevs/Rare/assets/10142751/f9989c71-bf44-40ae-8515-36dc324a4145)

**Comment by rjbprime** [comment]
Could also work for #254

**Comment by loathingKernel** [comment]
> `QT_SCALE_FACTOR=0.5`

Fractional values below 1 are not supported by Qt. Nothing we can do about it. Qt itself doesn't render correctly for values below 1. Closing as invalid.
