### ISSUE TITLE
[BUG] (???) Cannot log in through Browser.

### ISSUE THREAD

**Issue by JohnGhostly** [RareDevs/Rare#369]
**Describe the bug**

When attempting to login through browser the following error appears on a blank page:
`redacted`

**To Reproduce**

1. Install to root of a drive
2. Open Rare
3. check "browser" login option
4. click next
5. Click "Open Browser Option
6. See Error

**Expected behavior**

Login Through Epic API

**Screenshots**

`removed link`

**System information**

- Operating system: Windows 10
- Version 10.0.19045
- Installation method  Zip
- Python3 
- Vivaldi web browser

**Error message**

`redacted`

Log Shouldn't be applicable but will provide if needed

**Comment by loathingKernel** [comment]
I have removed the sensitive information from your bug report, I am leaving the link so you can delete the screenshot from the internet. Please read the text under the `Browser login` page. It contains instructions on how to log in and a huge fat warning about not posting this information publicly on the internet.

**Comment by loathingKernel** [comment]
![image](https://github.com/RareDevs/Rare/assets/142770/4b260e8b-a999-4c9d-804e-07291d58bc01)

**Comment by JohnGhostly** [comment]
> I have removed the sensitive information from your bug report, I am leaving the link so you can delete the screenshot from the internet. Please read the text under the `Browser login` page. It contains instructions on how to log in and a huge fat warning about not posting this information publicly on the internet.
Oops, my bad, I didn't even notice so thank you very much.

**Comment by loathingKernel** [comment]
Is this resolved? Can it be closed?
