### ISSUE TITLE
[ERROR]Install Error

### ISSUE THREAD

**Issue by mchssj** [RareDevs/Rare#380]
When i install Rare this error appears me

**System information**

Please complete the following information
- Operating system: Windows 11
- Version 23h2
- Installation method msi
- Python version 3.12

![Captura de pantalla 2024-02-04 012903](https://github.com/RareDevs/Rare/assets/143357176/708aa127-4632-4cca-8f4b-81c137461b8a)

**Comment by loathingKernel** [comment]
https://github.com/RareDevs/Rare/issues/375
