### ISSUE TITLE
AUTHORIZATRION CODE[Feature Request]

### ISSUE THREAD

**Issue by MATRIXBEE** [RareDevs/Rare#384]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MATRIXBEE** [comment]
WHAT IS AUTHORIZATION CODE

**Comment by loathingKernel** [comment]
> WHAT IS AUTHORIZATION CODE

Screaming will only stop you from getting help.

Read the description at the bottom of the login form.
