### ISSUE TITLE
Rare Gui Not Responding[BUG]

### ISSUE THREAD

**Issue by ggaryan** [RareDevs/Rare#391]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**

Please complete the following information
- Operating system: [e.g. Manjaro/Windows 10]
- Version [e.g. 1.6.2]
- Installation method [e.g. pip/msi/AppImage]
- Python version (if installed through `pip` or your package manager)

**Additional context**

**Error message**

You can find logs in these locations

| OS      | Path                                                     |
|---------|----------------------------------------------------------|
| Windows | `C:\Users\<username>\AppData\Local\Rare\Rare\cache\logs` |
| Linux   | `/home/<username>/.cache/Rare/Rare/logs`                 |
| masOS   | `/Users/<username>/Library/Caches/Rare/Rare/logs`        |

**Comment by loathingKernel** [comment]
Please feel the issue template properly.

**Comment by loathingKernel** [comment]
Closing this due to lack of information.
