### ISSUE TITLE
[BUG] Rare is not on the latest stable release on Winget

### ISSUE THREAD

**Issue by BOY0038v2** [RareDevs/Rare#395]
**Describe the bug**

Last version of Rare on winget is 1.10.7 (as you can see [here](https://github.com/microsoft/winget-pkgs/tree/master/manifests/d/Dummerle/Rare))
It needs to be updated to the latest version (1.10.11 as of today)
Thanks in advance.

**Comment by loathingKernel** [comment]
We do not manage the winget package ourselves. I will bring it up on their issues though and see if the maintainer can handle it.
