### ISSUE TITLE
[BUG] Rare logs out of epic when I log out of epic in my browser

### ISSUE THREAD

**Issue by chrrybmb64** [RareDevs/Rare#397]
**Describe the bug**

After logging in to epic using the browser method, rare will only stay logged in to epic if I stay logged in on the epic website. Logging out of the epic website logs me out of rare as well.

**To Reproduce**

1. Log into epic on rare via browser
2. After logging in, log out of the epic website
3. Close rare and then re-open it
4. Rare asks the user to log in again

**Expected behavior**

I expect to remain logged in on rare after logging out on epicgames.com

**Screenshots**

n/a

**System information**

Please complete the following information
- Operating system: Arch Linux
- Version: 1.10.11
- Installation method: `rare` aur package
- Python version: 3.11.8

**Additional context**

n/a

**Error message**

n/a

**Comment by loathingKernel** [comment]
When you log out from the browser, you invalidate the session during which the authorization code you used to log in into Rare was created, In a sense, it works "as intended".
