### ISSUE TITLE
[BUG] Rare crashes when clicking on game thumbnail

### ISSUE THREAD

**Issue by flurbudurbur** [RareDevs/Rare#398]
**Describe the bug**

**To Reproduce**

1. Go to `Games`
2. Click on any game thumbnail
3. Witness the crash

**Expected behavior**

Viewing the game information.

**Screenshots**

![Recording 2024-04-17 133810](https://github.com/RareDevs/Rare/assets/69259138/19aa654a-3de1-4573-b3a4-affc1803b3d6)

**System information**

Please complete the following information
- Operating system: Windows 11 Pro
- Version: 22H2 (Build number `22621.3447`)
- Rare Version: Garlic Crab
- Installation method: Originally via EXE, but upgraded via Winget
- Python version: 3.10.11

**Additional context**

N/A

**Error message**

```txt
[Rare] INFO: Launching Rare version 1.10.3
[Rare] INFO: Operating System: Windows
[Core] INFO: Trying to re-use existing login session...
[LaunchDialog] INFO: You are logged in
[RareCore] INFO: Got API results for COMBINED
[LaunchDialog] INFO: App starting
[Rare] INFO: Renewed session expires at 2024-04-17T17:26:32.391Z
[GameProcess] ERROR: 26b63c46de9e4dcc856b3c6b106b6777 (AER Memories of Old): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Sugar (Rocket League®): QLocalSocket::connectToServer: Invalid name
[WineResolver] INFO: Origin registry worker finished in 0.0s
[Rare] INFO: Launching Rare version 1.10.3
[Rare] INFO: Operating System: Windows
[Core] INFO: Trying to re-use existing login session...
[LaunchDialog] INFO: You are logged in
[RareCore] INFO: Got API results for COMBINED
[LaunchDialog] INFO: App starting
[Rare] INFO: Renewed session expires at 2024-04-17T17:26:32.391Z
[GameProcess] ERROR: 26b63c46de9e4dcc856b3c6b106b6777 (AER Memories of Old): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Sugar (Rocket League®): QLocalSocket::connectToServer: Invalid name
[WineResolver] INFO: Origin registry worker finished in 0.0s
```

**Comment by flurbudurbur** [comment]
> Even better, you could try reproducing it in the latest pre-release.

Well I have both good and bad news. I forgot to switch back and so this **is** the pre-release.

**Comment by flurbudurbur** [comment]
Alright, I seem to have figured out what the issue is. Because I originally installed it with the EXE and recently updated it with Winget. Winget just executed the MSI which uses the default location. I didn't have rare there. So turns out I had both 1.10.11 and 1.10.3 installed. I've uninstalled .3, ran the MSI for .11 and repaired the old "new" install and now we're good.

**Comment by loathingKernel** [comment]
The duplicated install is partly our fault and is an old issue, because the installer's signature was auto-generated each release. This issue was fixed a few versions back, so it shouldn't happen again.
