### ISSUE TITLE
[BUG] com.epicgames.launcher link

### ISSUE THREAD

**Issue by Splarkszter** [RareDevs/Rare#402]
**Describe the bug**
Gen i try to play the annoyingly awfull game that is GTAV, rocktar bullshit launcher tries to launch but it can't because i can't find epicgames launcher.
And for some reason rare isn't linked to com.epicgames.launcher

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**

Please complete the following information
- Operating system: [e.g. Manjaro/Windows 10]
- Version [e.g. 1.6.2]
- Installation method [e.g. pip/msi/AppImage]
- Python version (if installed through `pip` or your package manager)

**Additional context**

**Error message**

You can find logs in these locations

| OS      | Path                                                     |
|---------|----------------------------------------------------------|
| Windows | `C:\Users\<username>\AppData\Local\Rare\Rare\cache\logs` |
| Linux   | `/home/<username>/.cache/Rare/Rare/logs`                 |
| masOS   | `/Users/<username>/Library/Caches/Rare/Rare/logs`        |

**Comment by loathingKernel** [comment]
Start Rockstar Launcher before launching the game through Rare.

**Comment by Splarkszter** [comment]
Thank you. I was stressed by being forced to install the rockstar luncher. Sorry.

Yeah. I found the answer on the legendary repo. Thank you.
