### ISSUE TITLE
[BUG] False Update available Message ❗

### ISSUE THREAD

**Issue by techgamers2** [RareDevs/Rare#414]
**Describe the bug**
I updated my game using the Epic Games Launcher, but Rare still indicates that an update is available. I can't launch the game using the Fortnite shortcut created by the Rare launcher.

Rare is not syncing the updated version even though I have tried verifying the game files.

**To Reproduce**
When a Fortnite game update appears in the Rare launcher, close it and update through the Epic Games Launcher. After restarting the Rare launcher, it may still show that an update is available, even after restarting the PC.

**Screenrecord**
<details>
<summary>Screenrecord</summary>
Fortnite Version 30.10
<br>

https://github.com/RareDevs/Rare/assets/44696073/fc357233-4c9b-49f2-9a6a-ce7de4616279

</details>

**System information**
- Operating system: [Windows 10]
- Version [1.10.11]
- Installation method [msi]

**Additional context**
You can still launch the game using the "launch without version check" option in the Rare launcher, but you cannot launch it using the game's desktop shortcut created by the Rare launcher.
~ps I accidentally updated Fortnite through the Epic Launcher because it automatically updated when I opened the launcher to check my friend list.

**Logs Attached**
[Rare_24-06-19--13-15.log](https://github.com/user-attachments/files/15897766/Rare_24-06-19--13-15.log)
[RareLauncher_Fortnite_24-06-19--12-38.log](https://github.com/user-attachments/files/15897769/RareLauncher_Fortnite_24-06-19--12-38.log)

**Comment by loathingKernel** [comment]
Automatic sync was disabled some time ago because it caused issues specifically with Fortnite.  To fix the erroneous update message, uninstall Fortnite from Rare while having **checked** both `Keep files` and `Keep configuration` options in the uninstall dialog. You can then import the game again and it will be imported as the latest version. Verify the game and the message should disappear.

**Comment by loathingKernel** [comment]
This is not a bug in the regular sense, as breaching the barrier between EGL and Rare without user intervention could be considered a bug itself, so I am closing the issue. If the method I described above doesn't work, feel free to re-open it.

**Comment by techgamers2** [comment]
Thank you so much for your response and this project 👍..... your method worked perfectly. 👌❤️
