### ISSUE TITLE
[BUG] Shortcut icons represent the cover image, not the actual .exe file icon

### ISSUE THREAD

**Issue by Khalylexe** [RareDevs/Rare#432]
**Describe the bug**

The shortcut icons are showing a cover image instead of the actual .exe file icon. 

**To Reproduce**

1. Go to the game
2. Right Click on the cover
3. Click 'Create Desktop link'

**Expected behavior**

 shortcut icons to display the actual program's icon

**Screenshots**
![image](https://github.com/user-attachments/assets/6ac2a3c0-4ffa-4fdc-8193-13b1394bebe9)

**Comment by loathingKernel** [comment]
The implementation is meant to be cross-platform. This is the way it has to be to work consistently with the other platforms.
