### ISSUE TITLE
[BUG] cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by CartltonCrazeIsBackIGuess** [RareDevs/Rare#433]
**Describe the bug**
Whenever I open Rare I get this message:
cx_Freeze: Python error in main script
Traceback (most recent call last):
File
"C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-pack
ages\cx_Freeze\initscripts\___startup__.py", line 124, in run
File
"C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-pack
ages\cx_Freeze\initscripts\console.py", line 16, in run
File "rare\main.py", line 135, in <module>
File "rare\main.py", line 119, in main
File
"C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-pack
ages\rare\components\__init__.py", line 8, in <module>
File
"C:/hostedtoolcache/windows/Python/3.11.7/x64/Lib/site-pack
ages/PyQt5/__init__.py", line 69, in <module>
File
"C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-pack
ages\cx Freeze\hooks\pyqt5\append_to_init.py", line 22, in
<module>
File
"C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-pack
ages\cx_Freeze\hooks\pyqt5\append_to_init.py", line 7, in
_run
ImportError: DLL load failed while importing QtCore: The
specified module could not be found.

1. Open Rare

**Expected behavior**
For Rare to open

**Screenshots**
![Screenshot (1)](https://github.com/user-attachments/assets/4a8c6d64-59a6-4605-8eae-19ac39444738)

**System information**
Please complete the following information
- Operating system: Windows 11 IoT Enterprise LTSC
- Version: 24H2
- OS build: 26100.1457
- Installation method [msi]

**Comment by loathingKernel** [comment]
From the Readme:

Important: On recent version of Windows you should have MSVC 2015 installed, you can get it from here
