### ISSUE TITLE
[BUG] Error when start Rare GUI in Windows 11

### ISSUE THREAD

**Issue by homarck** [RareDevs/Rare#436]
**Describe the bug**

After install version 1.10.11, it show error message when start.

**To Reproduce**

1. Install Rare-1.10.11.msi
2. Run Rare.exe
3. See error

**Expected behavior**

When double clicking rare.exe, it should launch rare launcher.

**Screenshots**

![error](https://github.com/user-attachments/assets/273de959-2978-4c34-a13d-badc29947167)

**System information**

Please complete the following information
- Operating system: Windows 11 version 23H2
- Version: Rare-1.10.3.msi
- Installation method: .msi

**Error message**

[Rare_24-09-04--01-42.log](https://github.com/user-attachments/files/16874292/Rare_24-09-04--01-42.log)

**Comment by loathingKernel** [comment]
Try the latest pre-release from [here](https://github.com/RareDevs/Rare/releases/tag/1.10.11.343). If the problem persists, we possibly need to update the legendary version bundled with Rare/

**Comment by homarck** [comment]
> Try the latest pre-release from [here](https://github.com/RareDevs/Rare/releases/tag/1.10.11.343). If the problem persists, we possibly need to make a new release to update the legendary version bundled with Rare.

Hi, I just tested the latest pre-release and still have problem

![error 2](https://github.com/user-attachments/assets/1b023004-ef16-4424-b885-d104de74bbfd)

[Rare_24-09-05--21-51.log](https://github.com/user-attachments/files/16894647/Rare_24-09-05--21-51.log)

**Comment by homarck** [comment]
Hi, just an update for the latest pre-release. I downloaded the zip version and extracted to run rare.exe inside. This time no error message and I can see the GUI without problem. Then I download the msi version to install and run but this time it hold in the Launching windows. I need to kill the rara.exe task from task manager. Then go back to run the rare.exe in the extracted zip folder and got same problem. Afterward I uninstalled the msi version and run the zip version again but problem still exist. I attached the log for the success login and failed log for your reference. Please note that I don't have the error prompt in this release.

![freeze](https://github.com/user-attachments/assets/2a5e3da8-dcd7-46f0-b41e-6f5499a5c8ff)

[Rare_24-09-05--22-41.log](https://github.com/user-attachments/files/16895884/Rare_24-09-05--22-41.log)
[Rare_24-09-05--22-19.log](https://github.com/user-attachments/files/16895885/Rare_24-09-05--22-19.log)

**Comment by loathingKernel** [comment]
So according to your description and through the successful log, I can see that Rare showed its window. I cannot see an error in the failed log, just that it got stuck. Other than waiting longer for it to do something, you could try to run Rare with the `--debug` argument. It might provide more information in the debug log. I still think this could be an issue with Rare, and I hope I can somehow reproduce it.

Could you try legendary from the command line and see how it behaves, and could you find out which game is `Cajun` as it seems like it lacks the necessary metadata.

**Comment by loathingKernel** [comment]
Could you delete `%USERPROFILE\.config\legendary\assets.json%` and try launching Rare again as described in this issue? https://github.com/derrod/legendary/issues/633

**Comment by homarck** [comment]
Thanks! All good after deleted the file assets.json in the mentioned path. Thanks a lot for your help!
