### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Aideng1016** [RareDevs/Rare#451]
It says error traceback most recent call and then has a bunch of errors

1. Go to the zip file and exctract the rare.exe
2. Click on open rare.exe
3.  See error

I downloaded rare 2 months ago and it worked fine but for some reason it isn't working. I tried to download it from  https://github.com/RareDevs/Rare/releases/tag/1.10.11.371. but the error still popped up. 
![364806113-1b023004-ef16-4424-b885-d104de74bbfd](https://github.com/user-attachments/assets/d47e57f1-1c3a-408f-ac4c-625f48ffd9b5)
that is what the error looked like. I need rare to work or else I cant play my games it would be great if you could get back to me soon thanks.

**Comment by loathingKernel** [comment]
Closing in favor of the existing issue in #436. Please refer to that issue for what information could help us fix this issue and possible workarounds.

**Comment by loathingKernel** [comment]
https://github.com/RareDevs/Rare/issues/436#issuecomment-2334426437

**Comment by Aideng1016** [comment]
i tried the link on #436 and it didnt work
