### ISSUE TITLE
[BUG] Error cause hanging on app launch

### ISSUE THREAD

**Issue by KorewaLidesu** [RareDevs/Rare#463]
**Describe the bug**

Rare error on launching, ignore the error and start GUI hanging at 99%

**To Reproduce**

1. Open Rare
2. Wait till error occur

**Expected behavior**

Rare should launch-able.

**Screenshots**

![image](https://github.com/user-attachments/assets/eb968237-e8a1-4f14-ba3e-bbbf04cce76a)

**System information**

Please complete the following information
- Operating system: Windows 10 LTSC
- Version: [Pre-release 1.10.11.423](https://github.com/RareDevs/Rare/releases/tag/1.10.11.423)
- Installation method: Via MSI installation
- Python version: None

**Additional context**

None.

**Error message**

[Rare_24-10-10--12-32.log](https://github.com/user-attachments/files/17322627/Rare_24-10-10--12-32.log)

**Comment by loathingKernel** [comment]
Yeah, seems Rare cannot figure out the enconding of the Steam display name. Could you possibly post your display name here if that's OK with you? Temporarily you could try changing or removoming the display name as a workaround.

**Comment by KorewaLidesu** [comment]
It is "チルノ (Chiruno)" for display name.
Seem like latest release ([1.10.11](https://github.com/RareDevs/Rare/releases/tag/1.10.11)) working so I used that instead.

**Comment by loathingKernel** [comment]
I believe the fix above should work, but I do not have Windows available right now to test. Please give it a try through the latest pre-release and get back to me.
