### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AmmarTheGOAT9** [RareDevs/Rare#474]
I'm trying to launch Fortnite but nothing happens. I'm using Linux on my Pixelbook Go (as an experiment) and everything was going smoothly until I launched Fortnite. As I said earlier, Fortnite would not launch and would just stay on the same screen: no errors, no warnings, nothing. I need someone to help me with this because I'm not trying to reset Linux for the third time 😭.

**Comment by loathingKernel** [comment]
Fortnite does not work on anything but Windows. Try to replicate the issue with another game which doesn't have any form of anti-cheat.
