### ISSUE TITLE
[BUG] Cannot login though browser

### ISSUE THREAD

**Issue by freejool** [RareDevs/Rare#477]
**Describe the bug**

Epic rejects the authentication request.

**To Reproduce**

1. Click "Open Browser"
1. login Epic

**Expected behavior**

Some json format appears with token 

**Screenshots**

![image](https://github.com/user-attachments/assets/88f3b0a2-0a32-4b21-92a8-0f7d19a8f6a7)

**System information**

Please complete the following information
- Operating system: [Windows 10]
- Version [e.g. 1.10.11]
- Installation method [scoop]

**Additional context**

legendary 0.20.34 login is OK

**Error message**

nothing relavent

**Comment by loathingKernel** [comment]
Someone on our Discord server reported the same issue, and they ultimately identified it as being an issue with their ping booster software. Are you running any similar applications that manipulate your network traffic?

**Comment by freejool** [comment]
That is true. User issue.
